id: P010570
initial_creation_type: ocr
source_metadata:
  id: bdr:W28866
  title: དུནཧུཨང་བེན་ཏུཕ༹ན་ཡི་྾ཨུཨེ་ཝེན་྾ཨིཨན་ཇིང་ཡཨོ་༔་ཡི་ཞུ་ཇི་ཡན་ཇིཨུ་ཝེན་ཇི
  author: ''
  volumes:
    453a39f3271b491888552fc123df8f63:
      image_group_id: I4804
      title: ''
      volume_number: 1
      total_pages: 351
