id: ID7D31209
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T19:32:08+00:00'
last_modified: '2022-06-08T14:34:11.964691+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28866
  title: དུནཧུཨང་བེན་ཏུཕ༹ན་ཡི་྾ཨུཨེ་ཝེན་྾ཨིཨན་ཇིང་ཡཨོ་༔་ཡི་ཞུ་ཇི་ཡན་ཇིཨུ་ཝེན་ཇི
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E42:
      image_group_id: I4804
      title: ''
      total_pages: 351
      order: 1
      base_file: 4E42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
